models/contact.py
from utils.db import db

class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(50), nullable=False)
    phone = db.Column(db.Integer, nullable=False)

    def __init__(self, fullname, phone):
        self.fullname = fullname
        # self.email = email
        self.phone = phone

app.py
# Configuraciones del programa
from flask import Flask
# despues de crear nuestras rutas importamos el blueprint que creamos en routes/contacts.py
from routes.contacts import contacts
# momento de hacer las configs para nuestra base de datos
from flask_sqlalchemy import SQLAlchemy

from utils.db import db

app = Flask(__name__)

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///contacts.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False # Esta configuracion por defecto es True
db.init_app(app)
# al modulo sqlalchemy le pasamos como argumento app
# SQLAlchemy(app)
# al terminar con estas configs vamos a utils/db.py

# funcion para anhadir desde flask a blueprint
app.register_blueprint(contacts)

routes/contacts.py
# importar Blueprint
from flask import Blueprint, render_template, request, url_for, redirect

# importar la base de datos para traer los datos cuando se complete el form
from models.contact import Contact # Import el modelo de base de datos
from utils.db import db # Import de coneccion a la base de datos

# Crear una ruta con Blueprint
contacts = Blueprint("contacts", __name__)

# En vez de referirnos a app nos referimos a contacts

@contacts.route("/")
def index():
    mi_libreta = Contact.query.all()
    return render_template('index.html', libreta=mi_libreta)

# Trae los datos desde el form que esta en index.html
@contacts.route("/create", methods=['POST'])
def nuevo_contacto():
    fullname = request.form['fullname']
    phone = request.form['phone']

# new_contact devuelve un obj
    new_contact = Contact(fullname, phone)

# para guardar en la base de datos
    db.session.add(new_contact)
    db.session.commit()

    return redirect(url_for('contacts.index'))

@contacts.route("/update/<id>", methods=['GET' , 'POST'])
def update(id):
    contact = Contact.query.get(id)
    if request.method == 'POST':
        contact.fullname = request.form['fullname']
        contact.phone = request.form['phone']

        db.session.commit()
        return redirect(url_for('contacts.index'))
        
    return render_template('update.html', update=contact)

@contacts.route("/delete/<id>")
def delete(id):
    del_contact = Contact.query.get(id)
    db.session.delete(del_contact)
    db.session.commit()
    return redirect(url_for('contacts.index'))

# Exportar blueprint al archivo de configuracion app.py

templates/index.html
<!-- GET server returns data -->
<!-- POST sends HTML form data to the server -->

<form action="/create" method="POST" >
    <input type="text" name="fullname" placeholder=""/>
    <input type="text" name="phone" placeholder=""/>
    <button>Submit</button>

</form>

<div>
    {% for i in libreta %}

    <div>
        <h1>{{i.fullname}}</h1>
        <h1>{{i.phone}}</h1>
        <div>
            <a href="{{ url_for('contacts.update', id=i.id ) }}">Editar</a>
            <a href="{{ url_for('contacts.delete', id=i.id ) }}">Eliminar</a>
        </div>
    </div>

    {% endfor %}
</div>

templates/update.html
<form action="/update/{{ update.id }}" method="POST" >
    <input type="text" name="fullname" placeholder="" value="{{ update.fullname }}"/>
    <input type="text" name="phone" placeholder="" value="{{ update.phone }}"/>
    <button>Submit</button>

</form>